[functions]
  external_node_modules = ["express", "jsdom", "@resvg/resvg-js"]
  node_bundler = "esbuild"
  included_files = ["index.html", "styles.css"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
